# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_26th_Hackathon_9th' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_26th_Hackathon_9th
  
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  

  target 'SOPT_26th_Hackathon_9thTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOPT_26th_Hackathon_9thUITests' do
    # Pods for testing
  end

end
